In [1]:
import pandas as pd
import numpy as np

### Question 1

In [2]:
pd.__version__

'3.0.5'

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Question 2

In [5]:
df.index

RangeIndex(start=0, stop=10000, step=1)

### Question 3

In [6]:
df['fuel_type'].nunique()

3

### Question 4

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

### Question 5

In [8]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

### Question 6

In [9]:
df['horsepower'].median()

np.float64(254.0)

In [10]:
df['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [11]:
df['horsepower'] = df['horsepower'].fillna(252.0)

In [12]:
df['horsepower'].median()

np.float64(252.0)

### Question 7

In [21]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [22]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [27]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [29]:
XTX_inv = np.linalg.inv(XTX)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [30]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [33]:
w = (XTX_inv.dot(X.T)) * y
w

array([[-0.27509119, -0.02155228, -0.22895733,  0.35996837, -1.18162927,
         1.21328359,  0.27042587],
       [ 0.67427208,  0.13904122,  0.5529994 , -0.71637186,  2.63152339,
        -2.54924935, -0.49946567]])

In [34]:
w.sum()

np.float64(0.36919696904925475)